### ISSUE TITLE
Are there any plans for version 1.0.0 to accept running with Jekyll 3.3?

### ISSUE THREAD

**Issue by carlosdelfino** [gjtorikian/jekyll-last-modified-at#44] opened 2016-11-08 18:42 UTC
Hello.

Are there any plans for version 1.0.0 to accept running with Jekyll 3.3?

**Comment by ilg-ul** [comment] 2016-11-08 18:52
probably a duplicate of #41

**Comment by gjtorikian** [comment] 2019-11-17 14:50
Nope, sorry, 3.7 is going to be the minimum, GitHub Pages itself runs 3.8.

**Closed by gjtorikian** 2019-11-17 14:50 UTC
